<?php

$ccc = [
    "AF" => "+93",  // Afghanistan
    "AL" => "+355", // Albanien
    "DZ" => "+213", // Algerien
    "AD" => "+376", // Andorra
    "AO" => "+244", // Angola
    "AR" => "+54",  // Argentinien
    "AM" => "+374", // Armenien
    "AU" => "+61",  // Australien
    "AT" => "+43",  // Österreich
    "AZ" => "+994", // Aserbaidschan
    "BS" => "+1-242", // Bahamas
    "BH" => "+973", // Bahrain
    "BD" => "+880", // Bangladesch
    "BB" => "+1-246", // Barbados
    "BY" => "+375", // Weißrussland
    "BE" => "+32",  // Belgien
    "BZ" => "+501", // Belize
    "BJ" => "+229", // Benin
    "BT" => "+975", // Bhutan
    "BO" => "+591", // Bolivien
    "BA" => "+387", // Bosnien und Herzegowina
    "BW" => "+267", // Botswana
    "BR" => "+55",  // Brasilien
    "BN" => "+673", // Brunei
    "BG" => "+359", // Bulgarien
    "BF" => "+226", // Burkina Faso
    "BI" => "+257", // Burundi
    "KH" => "+855", // Kambodscha
    "CM" => "+237", // Kamerun
    "CA" => "+1",   // Kanada
    "CV" => "+238", // Kap Verde
    "KY" => "+1-345", // Kaimaninseln
    "CF" => "+236", // Zentralafrikanische Republik
    "TD" => "+235", // Tschad
    "CL" => "+56",  // Chile
    "CN" => "+86",  // China
    "CO" => "+57",  // Kolumbien
    "KM" => "+269", // Komoren
    "CG" => "+242", // Republik Kongo
    "CD" => "+243", // Demokratische Republik Kongo
    "CR" => "+506", // Costa Rica
    "CU" => "+53",  // Kuba
    "CY" => "+357", // Zypern
    "CZ" => "+420", // Tschechien
    "DK" => "+45",  // Dänemark
    "DJ" => "+253", // Dschibuti
    "DM" => "+1-767", // Dominica
    "DO" => "+1-809", // Dominikanische Republik
    "EC" => "+593", // Ecuador
    "EG" => "+20",  // Ägypten
    "SV" => "+503", // El Salvador
    "GQ" => "+240", // Äquatorialguinea
    "ER" => "+291", // Eritrea
    "EE" => "+372", // Estland
    "ET" => "+251", // Äthiopien
    "FJ" => "+679", // Fidschi
    "FI" => "+358", // Finnland
    "FR" => "+33",  // Frankreich
    "GA" => "+241", // Gabun
    "GM" => "+220", // Gambia
    "GE" => "+995", // Georgien
    "DE" => "+49",  // Deutschland
    "GH" => "+233", // Ghana
    "GR" => "+30",  // Griechenland
    "GD" => "+1-473", // Grenada
    "GT" => "+502", // Guatemala
    "GN" => "+224", // Guinea
    "GW" => "+245", // Guinea-Bissau
    "GY" => "+592", // Guyana
    "HT" => "+509", // Haiti
    "HN" => "+504", // Honduras
    "HK" => "+852", // Hongkong
    "HU" => "+36",  // Ungarn
    "IS" => "+354", // Island
    "IN" => "+91",  // Indien
    "ID" => "+62",  // Indonesien
    "IR" => "+98",  // Iran
    "IQ" => "+964", // Irak
    "IE" => "+353", // Irland
    "IL" => "+972", // Israel
    "IT" => "+39",  // Italien
    "JM" => "+1-876", // Jamaika
    "JP" => "+81",  // Japan
    "JO" => "+962", // Jordanien
    "KZ" => "+7",   // Kasachstan
    "KE" => "+254", // Kenia
    "KI" => "+686", // Kiribati
    "KP" => "+850", // Nordkorea
    "KR" => "+82",  // Südkorea
    "KW" => "+965", // Kuwait
    "KG" => "+996", // Kirgisistan
    "LA" => "+856", // Laos
    "LV" => "+371", // Lettland
    "LB" => "+961", // Libanon
    "LS" => "+266", // Lesotho
    "LR" => "+231", // Liberia
    "LY" => "+218", // Libyen
    "LI" => "+423", // Liechtenstein
    "LT" => "+370", // Litauen
    "LU" => "+352", // Luxemburg
    "MO" => "+853", // Macau
    "MK" => "+389", // Nordmazedonien
    "MG" => "+261", // Madagaskar
    "MW" => "+265", // Malawi
    "MY" => "+60",  // Malaysia
    "MV" => "+960", // Malediven
    "ML" => "+223", // Mali
    "MT" => "+356", // Malta
    "MH" => "+692", // Marshallinseln
    "MQ" => "+596", // Martinique
    "MR" => "+222", // Mauretanien
    "MU" => "+230", // Mauritius
    "YT" => "+262", // Mayotte
    "MX" => "+52",  // Mexiko
    "FM" => "+691", // Mikronesien
    "MD" => "+373", // Moldawien
    "MC" => "+377", // Monaco
    "MN" => "+976", // Mongolei
    "ME" => "+382", // Montenegro
    "MA" => "+212", // Marokko
    "MZ" => "+258", // Mosambik
    "MM" => "+95",  // Myanmar
    "NA" => "+264", // Namibia
    "NR" => "+674", // Nauru
    "NP" => "+977", // Nepal
    "NL" => "+31",  // Niederlande
    "NC" => "+687", // Neukaledonien
    "NZ" => "+64",  // Neuseeland
    "NI" => "+505", // Nicaragua
    "NE" => "+227", // Niger
    "NG" => "+234", // Nigeria
    "NU" => "+683", // Niue
    "NF" => "+672", // Norfolkinseln
    "MP" => "+1-670", // Nordmarianen
    "NO" => "+47",  // Norwegen
    "OM" => "+968", // Oman
    "PK" => "+92",  // Pakistan
    "PW" => "+680", // Palau
    "PA" => "+507", // Panama
    "PG" => "+675", // Papua-Neuguinea
    "PY" => "+595", // Paraguay
    "PE" => "+51",  // Peru
    "PH" => "+63",  // Philippinen
    "PL" => "+48",  // Polen
    "PT" => "+351", // Portugal
    "PR" => "+1-787", // Puerto Rico
    "QA" => "+974", // Katar
    "RO" => "+40",  // Rumänien
    "RU" => "+7",   // Russland
    "RW" => "+250", // Ruanda
    "RE" => "+262", // Réunion
    "BL" => "+590", // Saint-Barthélemy
    "SH" => "+290", // Saint Helena
    "KN" => "+1-869", // Saint Kitts und Nevis
    "LC" => "+1-758", // Saint Lucia
    "MF" => "+590", // Saint Martin
    "PM" => "+508", // Saint Pierre und Miquelon
    "VC" => "+1-784", // St. Vincent und die Grenadinen
    "WS" => "+685", // Samoa
    "SM" => "+378", // San Marino
    "ST" => "+239", // São Tomé und Príncipe
    "SA" => "+966", // Saudi-Arabien
    "SN" => "+221", // Senegal
    "RS" => "+381", // Serbien
    "SC" => "+248", // Seychellen
    "SL" => "+232", // Sierra Leone
    "SG" => "+65",  // Singapur
    "SX" => "+1-721", // Sint Maarten
    "SK" => "+421", // Slowakei
    "SI" => "+386", // Slowenien
    "SB" => "+677", // Salomonen
    "SO" => "+252", // Somalia
    "ZA" => "+27",  // Südafrika
    "GS" => "+500", // Südgeorgien und die Südlichen Sandwichinseln
    "SS" => "+211", // Südsudan
    "ES" => "+34",  // Spanien
    "LK" => "+94",  // Sri Lanka
    "SD" => "+249", // Sudan
    "SR" => "+597", // Suriname
    "SZ" => "+268", // Eswatini
    "SE" => "+46",  // Schweden
    "CH" => "+41",  // Schweiz
    "SY" => "+963", // Syrien
    "TW" => "+886", // Taiwan
    "TJ" => "+992", // Tadschikistan
    "TZ" => "+255", // Tansania
    "TH" => "+66",  // Thailand
    "TL" => "+670", // Osttimor
    "TG" => "+228", // Togo
    "TK" => "+690", // Tokelau
    "TO" => "+676", // Tonga
    "TT" => "+1-868", // Trinidad und Tobago
    "TN" => "+216", // Tunesien
    "TR" => "+90",  // Türkei
    "TM" => "+993", // Turkmenistan
    "TC" => "+1-649", // Turks- und Caicosinseln
    "TV" => "+688", // Tuvalu
    "UG" => "+256", // Uganda
    "UA" => "+380", // Ukraine
    "AE" => "+971", // Vereinigte Arabische Emirate
    "GB" => "+44",  // Vereinigtes Königreich
    "US" => "+1",   // Vereinigte Staaten
    "UY" => "+598", // Uruguay
    "UZ" => "+998", // Usbekistan
    "VU" => "+678", // Vanuatu
    "VE" => "+58",  // Venezuela
    "VN" => "+84",  // Vietnam
    "WF" => "+681", // Wallis und Futuna
    "YE" => "+967", // Jemen
    "ZM" => "+260", // Sambia
    "ZW" => "+263", // Simbabwe
];

$number = '+49 (2484) 919019-0';

if(str_starts_with($number, '+49')) {
  $number = '0'.substr(preg_replace("/[^0-9]/", "", $number), 2);
  echo $number;
} elseif(str_starts_with($number, '0049')) {
  $number = '0'.substr($number, 4);
  echo $number;
} elseif(preg_match('/^0{1}[1-9]*/', $number)) {
  $number = $number;
} elseif(preg_match('/^[1-9]{1}\d*/', $number)) {
  $number = $number;
} 

?>
